version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=opis
    networks:
      - opis
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "laravelapp"
    ports:
      - "8080:8080"
    networks:
      - opis
    command: bash -c "chown -R www-data:www-data /var/www/html/* && composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8080"

networks:
  opis:
    external: true
