version: '3.7'
services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=opis_manager
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            - opis
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'laravelapp'
        ports:
            - "8080:8080"
        networks:
            - opis
        command: bash -c "chown -R www-data:www-data /var/www/html/* && composer install && php artisan serve --host=0.0.0.0 --port=8080"

networks:
    opis:
        external: true