version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=opis
    networks:
      - default
  app:
    image: ghcr.io/unict-dmi/opis-manager-core:dev
    ports:
      - "8080:8080"
    networks:
      - default
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8080"
